// ===================================
// Application Configuration
// ===================================
export const CONFIG = {
  STORAGE_KEY: "visionboard_data",
  MONTHS: [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ],
  CATEGORIES: {
    career: { emoji: "💼", symbol: "◆", label: "Career", color: "#4A90E2" },
    health: { emoji: "💪", symbol: "●", label: "Health", color: "#5A9B8D" },
    finance: { emoji: "💰", symbol: "◇", label: "Finance", color: "#F0B429" },
    personal: {
      emoji: "💖",
      symbol: "♥",
      label: "Personal",
      color: "#E59AA0",
    },
    creative: {
      emoji: "🎨",
      symbol: "✦",
      label: "Creative",
      color: "#9F7AEA",
    },
  },
  PRIORITIES: {
    urgent: { emoji: "🔴", symbol: "!!!", label: "Urgent", color: "#C06C52" },
    high: { emoji: "🟠", symbol: "!!", label: "High", color: "#F4A261" },
    medium: { emoji: "🟡", symbol: "!", label: "Medium", color: "#4A9099" },
    low: { emoji: "🟢", symbol: "—", label: "Low", color: "#728B91" },
  },
  STATUSES: {
    "not-started": {
      emoji: "⏳",
      symbol: "○",
      label: "Not Started",
      color: "#6b7280",
    },
    "in-progress": {
      emoji: "🔄",
      symbol: "◐",
      label: "In Progress",
      color: "#3b82f6",
    },
    blocked: { emoji: "🚫", symbol: "✕", label: "Blocked", color: "#ef4444" },
    done: { emoji: "✅", symbol: "✓", label: "Done", color: "#10b981" },
  },
  AFFIRMATIONS: [
    "You're doing better than you think.",
    "Progress, not perfection.",
    "One step at a time is still moving forward.",
    "Your potential is limitless.",
    "Today is full of possibilities.",
    "You've overcome hard things before.",
    "Be patient with yourself.",
    "Small wins add up to big victories.",
    "You are capable of amazing things.",
    "Every expert was once a beginner.",
    "Focus on what you can control.",
    "Your journey is unique and valid.",
    "Rest is productive too.",
    "You don't have to be perfect to be worthy.",
    "Celebrate how far you've come.",
  ],
  LEVELS: {
    vision: { emoji: "✨", symbol: "✱", label: "Vision", color: "#8b5cf6" },
    milestone: { emoji: "🎯", symbol: "⬡", label: "Milestone", color: "#3b82f6" },
    focus: { emoji: "🔎", symbol: "⬢", label: "Focus", color: "#f59e0b" },
    intention: { emoji: "🌱", symbol: "•", label: "Intention", color: "#10b981" },
  },
  ACHIEVEMENTS: {
    firstGoal: {
      emoji: "🌱",
      symbol: "①",
      label: "First Steps",
      desc: "Created your first vision",
    },
    fiveGoals: {
      emoji: "⭐",
      symbol: "★",
      label: "Dreamer",
      desc: "Defined 5 milestones",
    },
    tenGoals: {
      emoji: "🌟",
      symbol: "✶",
      label: "Visionary",
      desc: "Cast 10 visions",
    },
    firstComplete: {
      emoji: "🎯",
      symbol: "◎",
      label: "Achiever",
      desc: "Accomplished your first milestone",
    },
    fiveComplete: {
      emoji: "🏆",
      symbol: "▲",
      label: "Champion",
      desc: "Accomplished 5 milestones",
    },
    weekStreak: {
      emoji: "🔥",
      symbol: "⚡",
      label: "Returning",
      desc: "Returned 7 days in a row",
    },
    monthStreak: {
      emoji: "💎",
      symbol: "◈",
      label: "Steady",
      desc: "Returned 30 days in a row",
    },
    planner: {
      emoji: "📋",
      symbol: "☰",
      label: "Planner",
      desc: "Completed a weekly review",
    },
    organizer: {
      emoji: "🗂️",
      symbol: "▤",
      label: "Organizer",
      desc: "Added subtasks to an intention",
    },
    reflector: {
      emoji: "💭",
      symbol: "◌",
      label: "Reflector",
      desc: "Added notes to a focus",
    },
  },
  // Activity-specific emojis for subcategories/tags
  ACTIVITY_EMOJIS: {
    cycling: "🚴",
    workout: "🏋️",
    family: "🏠",
    boating: "⛵",
    movie: "🎬",
    reading: "📚",
    dog: "🐕",
    cardio: "🏃",
    cooking: "🍳",
    "self-care": "🧘",
    gardening: "🪴",
    skating: "⛸️",
    video: "📹",
    tennis: "🎾",
    surfing: "🏄",
  } as Record<string, string>,
};
